## This configuration was generated by terraform-provider-oci

resource oci_containerengine_cluster export_Precog {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bassgonavy@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-04-17T16:15:57.880Z"
  }
  endpoint_config {
    is_public_ip_enabled = "false"
    nsg_ids = [
    ]
    subnet_id = "ocid1.subnet.oc1.iad.aaaaaaaa6m67vbghxh3agt57ofsfvkyg3ydupr2wizu5yiqwnhoih77astzq"
  }
  freeform_tags = {
    "OKEclusterName" = "Precog"
  }
  image_policy_config {
    is_policy_enabled = "false"
  }
  #kms_key_id = <<Optional value not found in discovery>>
  kubernetes_version = "v1.22.5"
  name               = "Precog"
  options {
    add_ons {
      is_kubernetes_dashboard_enabled = "false"
      is_tiller_enabled               = "false"
    }
    admission_controller_options {
      is_pod_security_policy_enabled = "false"
    }
    kubernetes_network_config {
      pods_cidr     = "10.244.0.0/16"
      services_cidr = "10.96.0.0/16"
    }
    persistent_volume_config {
      defined_tags = {
      }
      freeform_tags = {
        "OKEclusterName" = "Precog"
      }
    }
    service_lb_config {
      defined_tags = {
      }
      freeform_tags = {
        "OKEclusterName" = "Precog"
      }
    }
    service_lb_subnet_ids = [
      "ocid1.subnet.oc1.iad.aaaaaaaaedbdvnlux2s4queskude7dcmnhml5tm3mktqxs6v3kqjwyygbuiq",
    ]
  }
  vcn_id = "ocid1.vcn.oc1.iad.amaaaaaaclpbrqaave6fer246adckbgwwbsp7myl3jneui3ftqklimim4a6a"
}

resource oci_containerengine_node_pool export_pool1 {
  cluster_id     = oci_containerengine_cluster.export_Precog.id
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bassgonavy@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-04-17T16:15:59.663Z"
  }
  freeform_tags = {
    "OKEnodePoolName" = "pool1"
  }
  initial_node_labels {
    key   = "name"
    value = "Precog"
  }
  kubernetes_version = "v1.22.5"
  name               = "pool1"
  node_config_details {
    defined_tags = {
    }
    freeform_tags = {
      "OKEnodePoolName" = "pool1"
    }
    #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
    #kms_key_id = <<Optional value not found in discovery>>
    nsg_ids = [
    ]
    placement_configs {
      availability_domain = "pxsU:US-ASHBURN-AD-3"
      #capacity_reservation_id = <<Optional value not found in discovery>>
      subnet_id = "ocid1.subnet.oc1.iad.aaaaaaaa6gn2cjdi7gfqs2qddbylmsbmf6x6droztg4zigiu26gmyue7z4dq"
    }
    placement_configs {
      availability_domain = "pxsU:US-ASHBURN-AD-2"
      #capacity_reservation_id = <<Optional value not found in discovery>>
      subnet_id = "ocid1.subnet.oc1.iad.aaaaaaaa6gn2cjdi7gfqs2qddbylmsbmf6x6droztg4zigiu26gmyue7z4dq"
    }
    placement_configs {
      availability_domain = "pxsU:US-ASHBURN-AD-1"
      #capacity_reservation_id = <<Optional value not found in discovery>>
      subnet_id = "ocid1.subnet.oc1.iad.aaaaaaaa6gn2cjdi7gfqs2qddbylmsbmf6x6droztg4zigiu26gmyue7z4dq"
    }
    size = "3"
  }
  node_metadata = {
  }
  node_shape = "VM.Standard.E3.Flex"
  node_shape_config {
    memory_in_gbs = "64"
    ocpus         = "4"
  }
  node_source_details {
    #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
    image_id    = "ocid1.image.oc1.iad.aaaaaaaapfdqrbk6n4txcqv5h5da3d5wyfi4h7jweomf4y5wb3tw2mfmn4dq"
    source_type = "IMAGE"
  }
  #quantity_per_subnet = <<Optional value not found in discovery>>
  ssh_public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDmdpr+3oYefTO9nsu+5867TiTn+uA8FaotaqUT0m9yRU46okcZBmob9/pPwLIprvSy2Z/X+vkTdfe1PVVVhuXC7zwgYtfHSIlB4/J7UjjI1ZRu4p87gOXa/3rnpQzUgz0BT6D4klKL3OdtGMbJFHWlfNdJIIFgMX1BtqX0XUnhHxa9l+cXHr1A4HofgKvwOF7kFkheua8kMkifiFATyLdGBkNDbhVyba+iLgvSMb1FvvAgBVlNxFGVRJHLoAWF2WZrsva85yNuLWTbcoIZs4JiKHIcmcJ/GazC+H26OyD//de7CU1zwmobsWHxbLhVj0WR+3taztS95NfXw7HRpFb kenneth.bass@oracle.com\n"
  #subnet_ids = <<Optional value not found in discovery>>
}

