## This configuration was generated by terraform-provider-oci

resource oci_core_internet_gateway export_oke-igw-quick-Precog-7dcdc1d33 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bassgonavy@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-04-17T16:15:52.720Z"
  }
  display_name = "oke-igw-quick-Precog-7dcdc1d33"
  enabled      = "true"
  freeform_tags = {
  }
  vcn_id = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.id
}

resource oci_core_service_gateway export_oke-sgw-quick-Precog-7dcdc1d33 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bassgonavy@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-04-17T16:15:52.792Z"
  }
  display_name = "oke-sgw-quick-Precog-7dcdc1d33"
  freeform_tags = {
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = "ocid1.service.oc1.iad.aaaaaaaam4zfmy2rjue6fmglumm3czgisxzrnvrwqeodtztg7hwa272mlfna"
  }
  vcn_id = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.id
}

resource oci_core_subnet export_oke-bastionSubnet-Precog {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.30.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bassgonavy@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-04-17T20:27:22.021Z"
  }
  dhcp_options_id = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.default_dhcp_options_id
  display_name    = "oke-bastionSubnet-Precog"
  dns_label       = "okebastionsubne"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.id
}

resource oci_core_subnet export_oke-k8sApiEndpoint-subnet-quick-Precog-7dcdc1d33-regional {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.0.0/28"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bassgonavy@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-04-17T16:15:56.077Z"
  }
  dhcp_options_id = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.default_dhcp_options_id
  display_name    = "oke-k8sApiEndpoint-subnet-quick-Precog-7dcdc1d33-regional"
  dns_label       = "sub12209f2a0"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_oke-private-routetable-Precog-7dcdc1d33.id
  security_list_ids = [
    oci_core_security_list.export_oke-k8sApiEndpoint-quick-Precog-7dcdc1d33.id,
  ]
  vcn_id = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.id
}

resource oci_core_subnet export_oke-nodesubnet-quick-Precog-7dcdc1d33-regional {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.10.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bassgonavy@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-04-17T16:15:56.074Z"
  }
  dhcp_options_id = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.default_dhcp_options_id
  display_name    = "oke-nodesubnet-quick-Precog-7dcdc1d33-regional"
  dns_label       = "sub2c881b88d"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_oke-private-routetable-Precog-7dcdc1d33.id
  security_list_ids = [
    oci_core_security_list.export_oke-nodeseclist-quick-Precog-7dcdc1d33.id,
  ]
  vcn_id = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.id
}

resource oci_core_subnet export_oke-svclbsubnet-quick-Precog-7dcdc1d33-regional {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.20.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bassgonavy@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-04-17T16:15:55.981Z"
  }
  dhcp_options_id = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.default_dhcp_options_id
  display_name    = "oke-svclbsubnet-quick-Precog-7dcdc1d33-regional"
  dns_label       = "lbsub945739bd8"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.id
}

resource oci_core_private_ip export_ReverseConnectionIp {
  defined_tags = {
  }
  display_name = "ReverseConnectionIp"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.30.124"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljryr2zqpbcdfqwysutwdm2iayzmy3w6y5u3s7klxwc6huu6kqfsiza"
}

resource oci_core_private_ip export_ocid1-bastion-oc1-iad-amaaaaaaclpbrqaa7hzxs2vtoc3gh6ulqovijh6ikj5c4fnbjw4dfcxo3jeq {
  defined_tags = {
  }
  display_name = "ocid1.bastion.oc1.iad.amaaaaaaclpbrqaa7hzxs2vtoc3gh6ulqovijh6ikj5c4fnbjw4dfcxo3jeq"
  freeform_tags = {
  }
  hostname_label = "host-10-0-30-195"
  ip_address     = "10.0.30.195"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljryr2zqpbcdfqwysutwdm2iayzmy3w6y5u3s7klxwc6huu6kqfsiza"
}

resource oci_core_private_ip export_Service-VNIC-for-cluster-ocid1-cluster-oc1-iad-aaaaaaaamsnr7xyp6g4sb3cwxkibljxfzg6t34ohv3z5zlqkuchhgrjtgbfq {
  defined_tags = {
  }
  display_name = "Service VNIC for cluster ocid1.cluster.oc1.iad.aaaaaaaamsnr7xyp6g4sb3cwxkibljxfzg6t34ohv3z5zlqkuchhgrjtgbfq"
  freeform_tags = {
  }
  hostname_label = "chhgrjtgbfq"
  ip_address     = "10.0.0.14"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljrb76yntg63u7fqo4lewerf4knnoag43agqu3kalcigtydsigg54fa"
}

resource oci_core_vcn export_oke-vcn-quick-Precog-7dcdc1d33 {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bassgonavy@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-04-17T16:15:51.428Z"
  }
  display_name = "oke-vcn-quick-Precog-7dcdc1d33"
  dns_label    = "precog"
  freeform_tags = {
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-oke-vcn-quick-Precog-7dcdc1d33 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bassgonavy@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-04-17T16:15:51.428Z"
  }
  display_name     = "Default DHCP Options for oke-vcn-quick-Precog-7dcdc1d33"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "precog.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_nat_gateway export_oke-ngw-quick-Precog-7dcdc1d33 {
  block_traffic  = "false"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bassgonavy@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-04-17T16:15:52.787Z"
  }
  display_name = "oke-ngw-quick-Precog-7dcdc1d33"
  freeform_tags = {
  }
  public_ip_id = "ocid1.publicip.oc1.iad.aaaaaaaabqut36ebinvnjbpt2okcpkwdecv25jcvp33dceytubog3tcaibvq"
  vcn_id       = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.id
}

resource oci_core_route_table export_oke-private-routetable-Precog-7dcdc1d33 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bassgonavy@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-04-17T16:15:55.058Z"
  }
  display_name = "oke-private-routetable-Precog-7dcdc1d33"
  freeform_tags = {
  }
  route_rules {
    description       = "traffic to the internet"
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.export_oke-ngw-quick-Precog-7dcdc1d33.id
  }
  route_rules {
    description       = "traffic to OCI services"
    destination       = "all-iad-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = oci_core_service_gateway.export_oke-sgw-quick-Precog-7dcdc1d33.id
  }
  vcn_id = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.id
}

resource oci_core_default_route_table export_oke-public-routetable-Precog-7dcdc1d33 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bassgonavy@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-04-17T16:15:51.428Z"
  }
  display_name = "oke-public-routetable-Precog-7dcdc1d33"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.default_route_table_id
  route_rules {
    description       = "traffic to/from internet"
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_oke-igw-quick-Precog-7dcdc1d33.id
  }
}

resource oci_core_security_list export_oke-nodeseclist-quick-Precog-7dcdc1d33 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bassgonavy@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-04-17T16:15:52.815Z"
  }
  display_name = "oke-nodeseclist-quick-Precog-7dcdc1d33"
  egress_security_rules {
    description      = "Allow pods on one worker node to communicate with pods on other worker nodes"
    destination      = "10.0.10.0/24"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Access to Kubernetes API Endpoint"
    destination      = "10.0.0.0/28"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "6443"
      min = "6443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Kubernetes worker to control plane communication"
    destination      = "10.0.0.0/28"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "12250"
      min = "12250"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Path discovery"
    destination      = "10.0.0.0/28"
    destination_type = "CIDR_BLOCK"
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol  = "1"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Allow nodes to communicate with OKE to ensure correct start-up and continued functioning"
    destination      = "all-iad-services-in-oracle-services-network"
    destination_type = "SERVICE_CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "443"
      min = "443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "ICMP Access from Kubernetes Control Plane"
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol  = "1"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Worker Nodes access to Internet"
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    description = "Allow pods on one worker node to communicate with pods on other worker nodes"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "all"
    source      = "10.0.10.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Path discovery"
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/28"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "TCP access from Kubernetes Control Plane"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.0.0/28"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Inbound SSH traffic to worker nodes"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Allow bastion to worker nodes communication."
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.30.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.id
}

resource oci_core_security_list export_oke-k8sApiEndpoint-quick-Precog-7dcdc1d33 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bassgonavy@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-04-17T16:15:52.776Z"
  }
  display_name = "oke-k8sApiEndpoint-quick-Precog-7dcdc1d33"
  egress_security_rules {
    description      = "Allow Kubernetes Control Plane to communicate with OKE"
    destination      = "all-iad-services-in-oracle-services-network"
    destination_type = "SERVICE_CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "443"
      min = "443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "All traffic to worker nodes"
    destination      = "10.0.10.0/24"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Path discovery"
    destination      = "10.0.10.0/24"
    destination_type = "CIDR_BLOCK"
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol  = "1"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Allow access from api endpoint to bastion."
    destination      = "10.0.30.0/24"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "6443"
      min = "6443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    description = "External access to Kubernetes API endpoint"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "6443"
      min = "6443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Kubernetes worker to Kubernetes API endpoint communication"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.10.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "6443"
      min = "6443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Kubernetes worker to control plane communication"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.10.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "12250"
      min = "12250"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Path discovery"
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.10.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Allow bastion to Kubernetes API endpoint communication."
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.30.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "6443"
      min = "6443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.id
}

resource oci_core_default_security_list export_oke-svclbseclist-quick-Precog-7dcdc1d33 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bassgonavy@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-04-17T16:15:51.428Z"
  }
  display_name = "oke-svclbseclist-quick-Precog-7dcdc1d33"
  egress_security_rules {
    description      = "Allow bastion to Kubernetes API endpoint communication."
    destination      = "10.0.0.0/28"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "6443"
      min = "6443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Allow bastion to worker nodes communication."
    destination      = "10.0.10.0/24"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    description = "Allows ssh communication over the internet."
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_oke-vcn-quick-Precog-7dcdc1d33.default_security_list_id
}

