## This configuration was generated by terraform-provider-oci

data oci_objectstorage_namespace export_namespace {
  compartment_id = var.compartment_ocid
}
resource oci_objectstorage_bucket export_streaming-videos {
  access_type    = "NoPublicAccess"
  auto_tiering   = "InfrequentAccess"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/bassgonavy@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-01-29T04:21:51.671Z"
  }
  freeform_tags = {
    "video-type" = "family"
  }
  #kms_key_id = <<Optional value not found in discovery>>
  metadata = {
  }
  name                  = "streaming-videos"
  namespace             = data.oci_objectstorage_namespace.export_namespace.namespace
  object_events_enabled = "false"
  storage_tier          = "Standard"
  versioning            = "Disabled"
}

resource oci_objectstorage_object export_streaming-videos_object_1 {
  bucket = "streaming-videos"
  #cache_control = <<Optional value not found in discovery>>
  #content = <<Optional value not found in discovery>>
  content_disposition = "json"
  #content_encoding = <<Optional value not found in discovery>>
  #content_language = <<Optional value not found in discovery>>
  content_md5  = "7a9jQj5VIt3U5E7MQ3AjMg=="
  content_type = "application/octet-stream"
  #delete_all_object_versions = <<Optional value not found in discovery>>
  metadata = {
  }
  namespace = data.oci_objectstorage_namespace.export_namespace.namespace
  object    = "OC1_regions"
  #opc_sse_kms_key_id = <<Optional value not found in discovery>>
  #source = <<Optional value not found in discovery>>
  #source_uri_details = <<Optional value not found in discovery>>
  storage_tier = "InfrequentAccess"
}

resource oci_objectstorage_object export_streaming-videos_object_2 {
  bucket = "streaming-videos"
  #cache_control = <<Optional value not found in discovery>>
  #content = <<Optional value not found in discovery>>
  #content_disposition = <<Optional value not found in discovery>>
  #content_encoding = <<Optional value not found in discovery>>
  #content_language = <<Optional value not found in discovery>>
  content_md5  = "SGhYX9WZz2eDekxqIYk8TA=="
  content_type = "video/mp4"
  #delete_all_object_versions = <<Optional value not found in discovery>>
  metadata = {
  }
  namespace = data.oci_objectstorage_namespace.export_namespace.namespace
  object    = "fam4330e84be1734f3b8f9bcc9df3bef1c8.mp4"
  #opc_sse_kms_key_id = <<Optional value not found in discovery>>
  #source = <<Optional value not found in discovery>>
  #source_uri_details = <<Optional value not found in discovery>>
  storage_tier = "Standard"
}

resource oci_objectstorage_object export_streaming-videos_object_3 {
  bucket = "streaming-videos"
  #cache_control = <<Optional value not found in discovery>>
  #content = <<Optional value not found in discovery>>
  #content_disposition = <<Optional value not found in discovery>>
  #content_encoding = <<Optional value not found in discovery>>
  #content_language = <<Optional value not found in discovery>>
  content_md5  = "1Vvd+NYpEIee2fYFUiFJqA=="
  content_type = "video/mp4"
  #delete_all_object_versions = <<Optional value not found in discovery>>
  metadata = {
  }
  namespace = data.oci_objectstorage_namespace.export_namespace.namespace
  object    = "famSampleVideo_1280x720_1mb.mp4"
  #opc_sse_kms_key_id = <<Optional value not found in discovery>>
  #source = <<Optional value not found in discovery>>
  #source_uri_details = <<Optional value not found in discovery>>
  storage_tier = "Standard"
}

resource oci_objectstorage_preauthrequest export_par-bucket-20220202-2123 {
  access_type           = "AnyObjectRead"
  bucket                = "streaming-videos"
  bucket_listing_action = "Deny"
  name                  = "par-bucket-20220202-2123"
  namespace             = data.oci_objectstorage_namespace.export_namespace.namespace
  #object_name = <<Optional value not found in discovery>>
  time_expires = "2022-02-10T02:23:41.851Z"
}

resource oci_objectstorage_preauthrequest export_par-object-20220219-2027 {
  access_type           = "ObjectRead"
  bucket                = "streaming-videos"
  bucket_listing_action = ""
  name                  = "par-object-20220219-2027"
  namespace             = data.oci_objectstorage_namespace.export_namespace.namespace
  object_name           = "OC1_regions"
  time_expires          = "2022-02-27T01:27:30.858Z"
}

resource oci_objectstorage_preauthrequest export_par-bucket-20220219-2147 {
  access_type           = "AnyObjectRead"
  bucket                = "streaming-videos"
  bucket_listing_action = "Deny"
  name                  = "par-bucket-20220219-2147"
  namespace             = data.oci_objectstorage_namespace.export_namespace.namespace
  #object_name = <<Optional value not found in discovery>>
  time_expires = "2022-02-27T02:47:56.757Z"
}

resource oci_objectstorage_preauthrequest export_par-object-20220219-2029 {
  access_type           = "ObjectRead"
  bucket                = "streaming-videos"
  bucket_listing_action = ""
  name                  = "par-object-20220219-2029"
  namespace             = data.oci_objectstorage_namespace.export_namespace.namespace
  object_name           = "fam4330e84be1734f3b8f9bcc9df3bef1c8.mp4"
  time_expires          = "2022-02-27T01:29:03.986Z"
}

