version: '3'
services:
  rabbit: 
    image: rabbitmq:3.8.28-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    restart: always
  history: 
    image: history-api:v6.4
    build: 
      context: ./history-api
      dockerfile: dockerfile-dev
    container_name: history-api
    volumes: 
      - type: bind
        source: "C:\\Users\\kabass\\Desktop\\oci_mockro_service\\history-api"
        target: "/app/history-api"
    ports: 
    - "5002:5002"
    environment: 
      - PORT=5002
      - FLASK_APP=/app/history-api/run.py
      - VIDEO_STORAGE_HOST=storage-webserver
      - VIDEO_STORAGE_PORT=5001
      - FLASK_ENV=development
    depends_on:
     - rabbit
    restart: on-failure
  storage:
    image: storage-webserver:v6.4
    build: 
      context: ./storage-webserver
      dockerfile: dockerfile.dockerfile-dev
    container_name: storage-webserver
    volumes: 
      - type: bind
        source: "C:\\Users\\kabass\\Desktop\\oci_mockro_service\\storage-webserver"
        target: "/app"
    ports:
    - "5001:5001"
    environment:
      - PORT=5001
      - FLASK_APP=run.py
    depends_on:
     - rabbit
    restart: on-failure
  proxy:
    image: proxy-webserver:v6.4
    build: 
      context: ./proxy-webserver
      dockerfile: dockerfile-dev
    container_name: proxy-webserver
    volumes:
      - type: bind
        source: "C:\\Users\\kabass\\Desktop\\oci_mockro_service\\proxy-webserver"
        target: "/app/proxy-webserver"
    ports:
    - '5000:5000'
    environment: 
    - FLASK_APP=/app/proxy-webserver/run.py
    - VIDEO_STORAGE_HOST=storage-webserver
    - VIDEO_STORAGE_PORT=5001
    - FLASK_ENV=development
    - PORT=5000
    depends_on:
     - rabbit
    restart: on-failure