# syntax=docker/dockerfile:1
FROM python:3.9-slim-buster

WORKDIR /app
COPY requirements.txt /app/
COPY network/ /app/network
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
#ENV FLASK_APP=proxy-webserver/run.py
ENV FLASK_ENV=development
RUN apt-get update && apt-get install -y libaio1 wget unzip \
    && wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip \
    && unzip instantclient-basiclite-linuxx64.zip \
    && rm -f instantclient-basiclite-linuxx64.zip \
    && echo /app/instantclient* > /etc/ld.so.conf.d/oracle-instantclient.conf \
    && ldconfig
RUN cp -R /app/network instantclient_21_5/
ENV TNS_ADMIN="/app/instantclient_21_5/network/admin"
#    apt-get install net-tools \
#    apt-get install iputils-ping
#RUN python3 /app/history-api/history/receive.py
CMD [ "python3", "-m", "flask", "run", "-p", "5002", "--host=0.0.0.0"]
#RUN celery --app history.routes.celery worker --loglevel info
#CMD [ "python3", "history-api/run.py"]
#CMD [ "python3"]